repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
-   repo: https://github.com/awslabs/cfn-python-lint
    rev: v0.51.0 # The version of cfn-lint to use
    hooks:
    -   id: cfn-python-lint
        files: cloudformation/.*\.(json|yml|yaml)$
